"""
Django settings for drf_tutorial project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-b9xn219_t)_5p5c4ovllf5$-d)k7oyhxk26v3b=r!6h2i+gedm'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Django REST Framework
    'rest_framework',
    'rest_framework.authtoken',
    'django_filters',
    # Tutorial Apps - Progressive Learning Path
    'basics',      # Level 1: Serializers, APIViews, Basic CRUD
    'intermediate', # Level 2: ViewSets, Routers, Relationships
    'advanced',    # Level 3: Authentication, Permissions, Filtering, Pagination
    'expert',      # Level 4: Custom Actions, Throttling, Nested Serializers, Advanced Patterns
    # Swagger/OpenAPI Documentation
    'drf_spectacular',  # Beautiful API documentation
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'drf_tutorial.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'drf_tutorial.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
    # Example: Multiple database configuration
    # Uncomment to use multiple databases:
    # 'expert_db': {
    #     'ENGINE': 'django.db.backends.sqlite3',
    #     'NAME': BASE_DIR / 'expert_db.sqlite3',
    # },
    # 'analytics_db': {
    #     'ENGINE': 'django.db.backends.postgresql',
    #     'NAME': 'analytics',
    #     'USER': 'user',
    #     'PASSWORD': 'password',
    #     'HOST': 'localhost',
    # }
}

# Database Router for Multiple Database Handling
# This tells Django which database to use for which models
# Uncomment to enable:
# DATABASE_ROUTERS = ['expert.database_router.ExpertDatabaseRouter']


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# Media files (for file uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# ============================================================================
# CACHING CONFIGURATION
# ============================================================================
# Caching is like storing frequently accessed data in fast memory
# Real-life example: Like keeping your most-used tools on your desk
# instead of in a storage room - much faster to access!

# For development, we use local memory cache (simple and fast)
# For production, use Redis or Memcached (more powerful)
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        # This stores cache in your computer's RAM - very fast but lost on restart
        # Like a sticky note on your desk - fast to read but gone when you restart
        'LOCATION': 'unique-snowflake',  # Unique identifier for this cache
        'TIMEOUT': 300,  # Default: cache expires after 5 minutes (like food expiration date)
        'OPTIONS': {
            'MAX_ENTRIES': 1000,  # Maximum number of items in cache (like desk space limit)
        }
    }
}

# For production, use Redis (uncomment and configure):
# CACHES = {
#     'default': {
#         'BACKEND': 'django.core.cache.backends.redis.RedisCache',
#         'LOCATION': 'redis://127.0.0.1:6379/1',  # Redis server address
#     }
# }

# ============================================================================
# DJANGO REST FRAMEWORK CONFIGURATION
# ============================================================================

REST_FRAMEWORK = {
    # Authentication - How users are authenticated
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',  # For web browsers
        'rest_framework.authentication.TokenAuthentication',    # For API tokens
    ],
    
    # Permissions - Who can access what
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',  # Read for all, write for authenticated
    ],
    
    # Pagination - How to split large result sets
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
    
    # Filtering - How to filter/search results
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',  # Field filtering
        'rest_framework.filters.SearchFilter',                # Search across fields
        'rest_framework.filters.OrderingFilter',              # Ordering results
    ],
    
    # Throttling - Rate limiting to prevent abuse
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',  # For anonymous users
        'rest_framework.throttling.UserRateThrottle'    # For authenticated users
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '100/hour',        # Anonymous users: 100 requests per hour
        'user': '1000/hour',       # Authenticated users: 1000 requests per hour
        'burst': '60/minute',      # Burst rate: 60 requests per minute
        'sustained': '1000/hour',   # Sustained rate: 1000 requests per hour
        'employee_list': '30/minute',  # Employee list: 30 requests per minute
        'project_create': '10/hour',    # Project creation: 10 requests per hour
    },
    
    # Renderers - How responses are formatted
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',           # JSON format
        'rest_framework.renderers.BrowsableAPIRenderer',  # HTML browsable API
    ],
    
    # Schema Generator - For Swagger/OpenAPI documentation
    # This tells DRF to use drf-spectacular to generate API documentation
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    
    # Date/Time formatting
    'DATETIME_FORMAT': '%Y-%m-%d %H:%M:%S',
    'DATE_FORMAT': '%Y-%m-%d',
    'TIME_FORMAT': '%H:%M:%S',
}

# ============================================================================
# SWAGGER/OPENAPI DOCUMENTATION CONFIGURATION
# ============================================================================
# Swagger is like an interactive API manual - you can see all endpoints,
# test them, and understand what they do, all in a beautiful web interface.
# 
# Real-life example:
# Like a restaurant menu that shows pictures, descriptions, and prices,
# and you can even place orders directly from it!

SPECTACULAR_SETTINGS = {
    'TITLE': 'Django REST Framework Tutorial API',
    'DESCRIPTION': '''
    Complete DRF Tutorial API - From Basics to Expert
    
    This API demonstrates all Django REST Framework concepts:
    - **Basics**: Serializers, Views, CRUD operations
    - **Intermediate**: ViewSets, Routers, Relationships
    - **Advanced**: Authentication, Permissions, Filtering, Pagination
    - **Expert**: Caching, Throttling, Nested Serializers, Bulk Operations
    
    ## Authentication
    Most endpoints require authentication. Get your token from:
    - Admin panel: /admin/authtoken/token/
    - Or create via: POST /api/advanced/profiles/ (if available)
    
    ## Try It Out!
    Click on any endpoint below to see details and try it out!
    ''',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'COMPONENT_SPLIT_REQUEST': True,
    'SCHEMA_PATH_PREFIX': '/api/',
    'TAGS': [
        {'name': 'Basics', 'description': 'Level 1: Basic CRUD operations with serializers and views'},
        {'name': 'Intermediate', 'description': 'Level 2: ViewSets, Routers, and model relationships'},
        {'name': 'Advanced', 'description': 'Level 3: Authentication, permissions, filtering, and pagination'},
        {'name': 'Expert', 'description': 'Level 4: Caching, throttling, nested serializers, and advanced patterns'},
    ],
    'SWAGGER_UI_SETTINGS': {
        'deepLinking': True,
        'displayOperationId': True,
        'defaultModelsExpandDepth': 2,
        'defaultModelExpandDepth': 2,
        'displayRequestDuration': True,
        'docExpansion': 'list',
        'filter': True,
        'showExtensions': True,
        'showCommonExtensions': True,
    },
}

# ============================================================================
# LOGGING CONFIGURATION
# ============================================================================
# Logging is like keeping a diary of what your application does.
# It records important events, errors, and information for debugging and monitoring.
# 
# Real-life example:
# Like a flight recorder (black box) - it records everything that happens
# so you can understand what went wrong if there's a problem.
# 
# Log levels (from least to most severe):
# - DEBUG: Detailed information for debugging (like step-by-step notes)
# - INFO: General information about program execution (like "user logged in")
# - WARNING: Something unexpected but not an error (like "cache miss")
# - ERROR: An error occurred but program continues (like "failed to send email")
# - CRITICAL: Serious error that may cause program to stop (like "database down")

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    
    # Formatters - How log messages are formatted
    # Like choosing how to format a letter - formal, casual, etc.
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
            'datefmt': '%Y-%m-%d %H:%M:%S'
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
        'detailed': {
            'format': '[{asctime}] {levelname} in {module}.{funcName}: {message}',
            'style': '{',
            'datefmt': '%Y-%m-%d %H:%M:%S'
        },
    },
    
    # Filters - Decide which log records to process
    # Like a spam filter - decides which emails to keep
    'filters': {
        'require_debug_true': {
            '()': 'django.utils.log.RequireDebugTrue',
        },
    },
    
    # Handlers - Where to send log messages
    # Like different output channels - console, file, email, etc.
    'handlers': {
        # Console handler - prints to terminal
        # Like speaking out loud - everyone can hear
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'simple'
        },
        
        # File handler - writes to file
        # Like writing in a diary - permanent record
        'file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'logs' / 'drf_tutorial.log',
            'formatter': 'detailed',
        },
        
        # Error file handler - only errors and above
        # Like an error log book - only serious issues
        'error_file': {
            'level': 'ERROR',
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'logs' / 'errors.log',
            'formatter': 'verbose',
        },
        
        # Debug file handler - only in development
        # Like detailed notes - only when debugging
        'debug_file': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'logs' / 'debug.log',
            'formatter': 'verbose',
            'filters': ['require_debug_true'],
        },
    },
    
    # Loggers - Define which parts of application log what
    # Like different departments - each has its own logging rules
    'loggers': {
        # Django framework logs
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,  # Don't pass to parent logger
        },
        
        # DRF logs
        'rest_framework': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        
        # Expert app logs (signals, context managers, etc.)
        'expert': {
            'handlers': ['console', 'file', 'error_file'],
            'level': 'DEBUG',
            'propagate': False,
        },
        
        # All other application logs
        'basics': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'intermediate': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'advanced': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
    },
    
    # Root logger - catches everything not handled by specific loggers
    # Like a safety net - catches anything that falls through
    'root': {
        'handlers': ['console', 'file'],
        'level': 'WARNING',
    },
}
